accounts/urls.py
from django.contrib.auth import views as auth_view
from django.urls import include, path, re_path, reverse_lazy
from rest_framework import routers

from . import views
from .forms import CustomPasswordResetForm
from .views import CustomUserViewSet, ProfileViewSet

app_name = 'accounts'

router = routers.DefaultRouter()
router.register(r'users', CustomUserViewSet, basename='user')
router.register(r'profiles', ProfileViewSet, basename='profile')

urlpatterns = [
    path('', include(router.urls)),
    # path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,40})/$',
            views.activate_user, name='activate_user'),

    path('password_reset/',
         auth_view.PasswordResetView.as_view(
             template_name='accounts/password_reset_form.html',
             email_template_name='accounts/password_reset_email.html',
             success_url=reverse_lazy('accounts:password_reset_done'),
             form_class=CustomPasswordResetForm,
         ),
         name='password_reset'),
    path('password_reset/done/',
         auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url=reverse_lazy('accounts:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_view.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html',
         ),
         name='password_reset_complete'),

]

drf_store/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from drf_store import settings

router = DefaultRouter()

schema_view = get_schema_view(
    title="Book store",
    description="API for book store",
    version="1.0.0"
)

urlpatterns = [
    path('account/', include('accounts.urls', namespace='accounts')),
    path('service/', include('services.urls', namespace='services')),
    path('api-auth/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('items/', include('items.urls', namespace='items')),
    path('openapi', schema_view, name='openapi-schema'),
    path('swagger-ui/',
         TemplateView.as_view(
             template_name='swagger/swagger-ui.html',
             extra_context={'schema_url': 'openapi-schema'}
         ),
         name='swagger-ui'),
    path('', include(router.urls))
]

# Add prefix api for url
urlpatterns = [path(settings.API_PREFIX_URL, include(urlpatterns))]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

items/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework import routers

from .views import (AuthorViewSet, BookViewSet, BrandViewSet, CategoryViewSet,
                    FigureViewSet, GenreViewSet, ItemViewSet, LanguageViewSet,
                    MagazineViewSet, PublisherViewSet)

app_name = 'items'

router = routers.DefaultRouter()
router.register(r'languages', LanguageViewSet)
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'authors', AuthorViewSet)
router.register(r'genres', GenreViewSet)
router.register(r'publishers', PublisherViewSet)
router.register(r'brands', BrandViewSet)
router.register(r'items', ItemViewSet, basename='item')
router.register(r'books', BookViewSet, basename='book')
router.register(r'magazines', MagazineViewSet, basename='magazine')
router.register(r'figures', FigureViewSet, basename='figure')

urlpatterns = [
    path('', include(router.urls)),
    # path('', views.ItemsListView.as_view(), name='home'),
    # path('category/<str:cat>', views.CategoryListView.as_view(), name='category'),
    # path('type/<str:type>', views.TypeListView.as_view(), name='type'),
    # path('<slug:slug>/', views.ItemDetailView.as_view(), name='item')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import csv
import logging
from smtplib import SMTPDataError

from django.contrib import admin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.managers import CustomUserManager
from utils.validators import validate_phone

logger = logging.getLogger(__name__)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username_validator = ASCIIUsernameValidator()

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True, max_length=50)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_absolute_url(self):
        return reverse('accounts:account', kwargs={'pk': self.pk})


class Region(models.Model):
    region = models.CharField(_('Регион'), max_length=50)
    country = models.CharField(_('Страна'), max_length=50)

    class Meta:
        unique_together = ['region', 'country']
        verbose_name = _('region')
        verbose_name_plural = _('regions')
        ordering = ('region',)

    def __str__(self):
        return f'{self.region}, {self.country}'

    @staticmethod
    def import_from_csv(file_name: str):
        """
        Import regions from csv to database
        :param file_name:
        :return:
        """
        with open(file_name) as file:
            reader = csv.reader(file)
            return Region.objects.bulk_create(
                [Region(region=row[2], country='Россия') for row in reader][1:],
                ignore_conflicts=True
            )


class Profile(models.Model):
    user = models.OneToOneField(to=CustomUser, related_name='profile', on_delete=models.CASCADE)
    phone = models.CharField(_('Phone'), max_length=20, validators=[validate_phone], blank=True)
    birthday = models.DateField(_('Birthday'), blank=True, null=True)
    region = models.ForeignKey(to=Region, blank=True, null=True, on_delete=models.SET_NULL)
    currency = models.PositiveIntegerField(_('Virtual currency'), default=0, blank=True)
    email_confirmed = models.BooleanField(_('Email confirmed'), default=False)

    @property
    def age(self):
        today = timezone.now()
        if self.birthday is not None:
            return today.year - self.birthday.year - \
                   ((today.month, today.day) < (self.birthday.month, self.birthday.day))

    @property
    @admin.display(description=_('Full name'))
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return self.user.email

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        try:
            old_currency = Profile.objects.get(pk=self.pk).currency
            if old_currency != self.currency:
                try:
                    self.user.email_user(subject='Change values',
                                         message=f'Currency = {self.currency}')
                except SMTPDataError:
                    logger.error('Сообщение не было отправлено', exc_info=True)
        except Profile.DoesNotExist:
            pass
        super(Profile, self).save()

    def is_adult(self):
        if self.age:
            return True if self.age >= 18 else False
        return False

accounts/views.py
import logging

from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView
from rest_framework import status, viewsets
from rest_framework.decorators import action, api_view
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework_simplejwt.exceptions import TokenError
from rest_framework_simplejwt.token_blacklist.models import OutstandingToken
from rest_framework_simplejwt.tokens import RefreshToken

from accounts.forms import SendEmailForm
from accounts.models import CustomUser, Profile
from accounts.permissions import UserPermission
from accounts.serializers import (ChangePasswordSerializer,
                                  GetCustomUserSerializer,
                                  GetProfileSerializer,
                                  PostCustomUserSerializer,
                                  PostProfileSerializer)
from accounts.tokens import account_activation_token

logger = logging.getLogger(__name__)


class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = PostCustomUserSerializer
    permission_classes = [UserPermission]

    MAP_ACTION_TO_SERIALIZER = {
        'list': GetCustomUserSerializer,
        'create': PostCustomUserSerializer,
        'retrieve': GetCustomUserSerializer,
    }

    def get_serializer_class(self):
        return self.MAP_ACTION_TO_SERIALIZER.get(self.action, self.serializer_class)

    @action(methods=['post'], detail=False, permission_classes=[AllowAny])
    def registration(self, request):
        """Регистрация нового пользователя"""
        return self.create(request)

    @action(methods=['PATCH'], detail=True, permission_classes=[UserPermission],
            serializer_class=ChangePasswordSerializer)
    def change_password(self, request, pk=None):
        user = self.get_object()
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(user=user)
        return Response({"Status": "OK"}, status=status.HTTP_200_OK)

    @action(methods=['post'], detail=False, permission_classes=[IsAuthenticated])
    def logout(self, request):
        """Logout user"""
        try:
            user_id = request.auth.payload['user_id']
            tokens = OutstandingToken.objects.filter(user_id=user_id)
            for token in tokens:
                RefreshToken(token).blacklist()
        except KeyError:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        except TokenError:
            pass

        return Response(data={"Logout": "OK"}, status=status.HTTP_205_RESET_CONTENT)


class ProfileViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = PostProfileSerializer
    permission_classes = [UserPermission]

    MAP_ACTION_TO_SERIALIZER = {
        'list': GetProfileSerializer,
        'create': PostProfileSerializer,
        'retrieve': GetProfileSerializer,
    }

    def get_serializer_class(self):
        return self.MAP_ACTION_TO_SERIALIZER.get(self.action, self.serializer_class)


class SendEmailView(SuccessMessageMixin, PermissionRequiredMixin, FormView):
    model = CustomUser
    template_name = 'admin/accounts/customuser/change_form.html'
    model_admin = None
    form_class = SendEmailForm
    success_url = reverse_lazy('admin:accounts_customuser_changelist')
    permission_required = ('accounts.view_customuser',)

    success_message = _('Email sended to %(email)s.')

    def get_object(self, request, **kwargs):
        user_id = self.kwargs['user_id']
        return CustomUser.objects.get(id=user_id)

    def get(self, request, **kwargs):
        user_id = self.kwargs['user_id']
        obj = self.get_object(request, **kwargs)
        context = self.get_context_data()
        form = SendEmailForm(instance=obj, initial={'body': f'Dear {obj.first_name}, ', 'subject': '[DJANGO ADMIN]'})
        context['form'] = form
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        obj = self.get_object(request, **kwargs)
        form = self.get_form()
        if form.is_valid():
            obj.email_user(subject=form.cleaned_data['subject'], message=form.cleaned_data['body'])
            logger.info(f'Email sent {request.user.email}')
            return self.form_valid(form)
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        return {
            **self.model_admin.admin_site.each_context(self.request),
            **super().get_context_data(**kwargs),
            'opts': CustomUser._meta,
            'has_view_permission': self.model_admin.has_view_permission(self.request),
            'title': _('Send email'),
            'add': '',
            'change': '',
            'save_as': '',
            'has_add_permission': False,
            'has_change_permission': False,
            'has_editable_inline_admin_formsets': False,
            'has_delete_permission': False,
        }


@api_view()
def activate_user(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64)
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
        logger.error(f'Invalid uid user for activation')

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        logger.info(f'Activate user {user}')
        return Response(data={"Activation": "Success"}, status=status.HTTP_200_OK)
    else:
        return Response(status=status.HTTP_400_BAD_REQUEST)

accounts/templates/accounts/account_activation_email.html
{% load i18n %}

{% autoescape off %}
{% translate 'Hi' %} {{ user.username }},

{% translate 'Please click on the link below to confirm your registration:' %}

http://{{ domain }}{% url 'accounts:activate_user' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/account_activation_invalid.html
{% extends 'root_site.html' %}

{% load i18n %}

{% block content %}
    <h2>{% translate 'Something is wrong.' %}</h2>
{% endblock %}

accounts/templates/accounts/account_activation_sent.html
{% extends 'root_site.html' %}

{% load i18n %}

{% block content %}
    <h2>{% translate 'Please confirm your email address to complete the registration.' %}</h2>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "root_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'items:home' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset' %}
</div>
{% endblock %}

{% block content %}

<p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{% url 'accounts:login' %}">{% translate 'Log in' %}</a></p>

{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "root_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'items:home' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset confirmation' %}
</div>
{% endblock %}

{% block content %}

{% if validlink %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
    <div class="form-row field-password1">
        {{ form.new_password1.errors }}
        <label for="id_new_password1">{% translate 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="form-row field-password2">
        {{ form.new_password2.errors }}
        <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <input type="submit" value="{% translate 'Change my password' %}">
</fieldset>
</form>

{% else %}

<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "root_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'items:home' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset' %}
</div>
{% endblock %}

{% block content %}

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "root_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'items:home' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset' %}
</div>
{% endblock %}

{% block content %}

<p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>

<form method="post">{% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-email">
        {{ form.email.errors }}
        <label for="id_email">{% translate 'Email address:' %}</label>
        {{ form.email }}
    </div>
    <input type="submit" value="{% translate 'Reset my password' %}">
</fieldset>
</form>

{% endblock %}