drf_store/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.schemas import get_schema_view
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from drf_store import settings

router = DefaultRouter()

schema_view = get_schema_view(
    title="Book store",
    description="API for book store",
    version="1.0.0"
)

urlpatterns = [
    path('account/', include('accounts.urls', namespace='accounts')),
    path('service/', include('services.urls', namespace='services')),
    path('api-auth/', include('rest_framework.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('items/', include('items.urls', namespace='items')),
    path('openapi', schema_view, name='openapi-schema'),
    path('swagger-ui/',
         TemplateView.as_view(
             template_name='swagger/swagger-ui.html',
             extra_context={'schema_url': 'openapi-schema'}
         ),
         name='swagger-ui'),
    path('', include(router.urls))
]

# Add prefix api for url
urlpatterns = [path(settings.API_PREFIX_URL, include(urlpatterns))]

urlpatterns += [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

items/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework import routers

from .views import (AuthorViewSet, BookViewSet, BrandViewSet, CategoryViewSet,
                    FigureViewSet, GenreViewSet, ItemViewSet, LanguageViewSet,
                    MagazineViewSet, PublisherViewSet)

app_name = 'items'

router = routers.DefaultRouter()
router.register(r'languages', LanguageViewSet)
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'authors', AuthorViewSet)
router.register(r'genres', GenreViewSet)
router.register(r'publishers', PublisherViewSet)
router.register(r'brands', BrandViewSet)
router.register(r'items', ItemViewSet, basename='item')
router.register(r'books', BookViewSet, basename='book')
router.register(r'magazines', MagazineViewSet, basename='magazine')
router.register(r'figures', FigureViewSet, basename='figure')

urlpatterns = [
    path('', include(router.urls)),
    # path('', views.ItemsListView.as_view(), name='home'),
    # path('category/<str:cat>', views.CategoryListView.as_view(), name='category'),
    # path('type/<str:type>', views.TypeListView.as_view(), name='type'),
    # path('<slug:slug>/', views.ItemDetailView.as_view(), name='item')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('history/', views.HistoryViewSet.as_view(actions={
        'get': 'list'
    }), name='history'),
    path('cart/', views.CartViewSet.as_view(actions={
        'get': 'get_cart',
        'patch': 'partial_update',
        'put': 'update',
    }), name='cart'),
    path('cart/<int:pk>/', views.CartViewSet.as_view(actions={
        'delete': 'delete_service'
    }), name='cart-delete-service'),
    path('purchase/', views.PurchaseViewSet.as_view(actions={
        'post': 'create',
    }), name='purchase'),
    path('rent/', views.RentViewSet.as_view(actions={
        'post': 'create',
    }), name='rent'),
    path('rent/<int:pk>/', views.RentViewSet.as_view(actions={
        'get': 'retrieve',
    }), name='rent-get')
]

templates/root_site.html
{% extends "admin/base_site.html" %}

{% load items_extras services_extras i18n %}

{% block title %} {{ title }} {% endblock %}

{% block branding %}
    <h1 id="site-name"><a href="{% url 'items:home' %}">{{ site_header|default:_('Book store') }}</a></h1>
{% endblock %}

{% block content_title %}{% endblock %}

{% block content %}
    <div class="content" style="display: flex; gap: 2rem;">
        <section class="menu">
            <section class="menu__type">
                <h2>{% translate 'Товары' %}</h2>
                {% list_type %}
            </section>

            <section class="menu__category">
                <h2>{% translate 'Категории' %}</h2>
                {% list_category user %}
            </section>

        </section>

        <section class="main-content" style="width: 75%;">
            {% block main-content %}{% endblock %}
        </section>

        <section class="account" style="right: 5em; position: absolute;">
            {% if  request.user.id %}
                <h3>Привет, {{ request.user.first_name }}</h3>
                <p><a href="{% url 'accounts:account' request.user.id %}"> {% translate 'Account' %} </a></p>
                <p><a href="{% url 'services:cart' %}"> {% translate 'Корзина' %} ({% count_items request.user %}) </a></p>
                <a href="{% url 'accounts:logout' %}"> {% translate 'Выйти' %} </a><br>
            {% else %}
                <p><a href="{% url 'accounts:login' %}"> {% translate 'Login' %} </a></p>
                <a href="{% url 'accounts:registration' %}"> {% translate 'Registration' %} </a>
            {% endif %}
            <form>
                <br><br>
                <p><input type="search" name="search_item" formaction="{% url 'items:home' %}" placeholder={% translate "Search" %}></p>
            </form>
        </section>
    </div>
{% endblock %}